spring:
  application:
    name: seckill-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: DEFAULT_GROUP
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: DEFAULT_GROUP
        file-extension: yaml
        shared-configs:
          - data-id: common-config.yaml
            refresh: true
        refresh-enabled: true
  config:
    import:
      - optional:nacos:seckill-service.yaml
      - optional:nacos:common-config.yaml
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/seckill_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: mt127715318
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: seckill-order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.demo.order.mq

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: "replace-with-at-least-32-characters-secret-key!!"
    expire-ms: 86400000

# Sentinel 配置
sentinel:
  transport:
    dashboard: ${SENTINEL_DASHBOARD:localhost:8080}
    port: 8719
  datasource:
    ds1:
      nacos:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        dataId: ${spring.application.name}-sentinel
        groupId: DEFAULT_GROUP
        rule-type: flow